"""Professional starter macros for the Macro editor. Exactly 100 SQL/Python examples."""

PYTHON_MACROS = [
    ("01 — Shape", "df.shape"), ("02 — Head", "df.head(10)"), ("03 — Tail", "df.tail(10)"),
    ("04 — Info", "df.info()"), ("05 — Dtypes", "df.dtypes"), ("06 — Describe", "df.describe(include='all')"),
    ("07 — Missing", "df.isna().sum().sort_values(ascending=False)"), ("08 — Missing %", "100 * df.isna().mean().sort_values(ascending=False)"),
    ("09 — Duplicates", "df.duplicated().sum()"), ("10 — Unique counts", "df.nunique().sort_values(ascending=False)"),
    ("11 — Numeric columns", "df.select_dtypes(include='number').columns.tolist()"), ("12 — Categorical columns", "df.select_dtypes(exclude='number').columns.tolist()"),
    ("13 — Correlation", "df.select_dtypes(include='number').corr()"), ("14 — Covariance", "df.select_dtypes(include='number').cov()"),
    ("15 — Value counts", "df['column'].value_counts(dropna=False)"), ("16 — Normalize values", "df['column'].value_counts(normalize=True, dropna=False)"),
    ("17 — Top rows", "df.nlargest(10, 'column')"), ("18 — Bottom rows", "df.nsmallest(10, 'column')"),
    ("19 — Sort ascending", "df.sort_values('column')"), ("20 — Sort descending", "df.sort_values('column', ascending=False)"),
    ("21 — Filter", "df.loc[df['column'] > 0]"), ("22 — Multi-filter", "df.loc[(df['a'] > 0) & (df['b'] == 'x')]") ,
    ("23 — Query", "df.query('value > 0')"), ("24 — Select columns", "df[['a', 'b', 'c']]") ,
    ("25 — Rename", "df.rename(columns={'old':'new'})"), ("26 — Drop column", "df.drop(columns=['column'])"),
    ("27 — Drop duplicates", "df.drop_duplicates()"), ("28 — Fill numeric mean", "df['column'].fillna(df['column'].mean())"),
    ("29 — Fill median", "df['column'].fillna(df['column'].median())"), ("30 — Fill category", "df['column'].fillna('Unknown')"),
    ("31 — To datetime", "df['date'] = pd.to_datetime(df['date'], errors='coerce')"), ("32 — Year", "df['date'].dt.year"),
    ("33 — Month", "df['date'].dt.month"), ("34 — Day", "df['date'].dt.day"), ("35 — Day of week", "df['date'].dt.dayofweek"),
    ("36 — String length", "df['text'].astype(str).str.len()"), ("37 — Lowercase", "df['text'].astype(str).str.lower()"),
    ("38 — Uppercase", "df['text'].astype(str).str.upper()"), ("39 — Strip spaces", "df['text'].astype(str).str.strip()"),
    ("40 — Replace text", "df['text'].astype(str).str.replace('old','new', regex=False)"),
    ("41 — Group sum", "df.groupby('category')['value'].sum()"), ("42 — Group mean", "df.groupby('category')['value'].mean()"),
    ("43 — Group median", "df.groupby('category')['value'].median()"), ("44 — Group count", "df.groupby('category').size()"),
    ("45 — Group multiple", "df.groupby(['a','b'])['value'].agg(['count','mean','sum'])"),
    ("46 — Pivot", "df.pivot_table(index='a', columns='b', values='value', aggfunc='mean')"),
    ("47 — Crosstab", "pd.crosstab(df['a'], df['b'])"), ("48 — Rank", "df['value'].rank(method='dense', ascending=False)"),
    ("49 — Percentile", "df['value'].quantile([.25,.5,.75])"), ("50 — IQR", "df['value'].quantile(.75) - df['value'].quantile(.25)"),
]
SQL_MACROS = [
    ("51 — Select", "SELECT * FROM data LIMIT 100;"), ("52 — Count rows", "SELECT COUNT(*) FROM data;"),
    ("53 — Distinct", "SELECT DISTINCT column FROM data;"), ("54 — Missing", "SELECT COUNT(*) FROM data WHERE column IS NULL;"),
    ("55 — Numeric summary", "SELECT MIN(value), MAX(value), AVG(value), STDDEV_POP(value) FROM data;"),
    ("56 — Group sum", "SELECT category, SUM(value) FROM data GROUP BY category ORDER BY SUM(value) DESC;"),
    ("57 — Group mean", "SELECT category, AVG(value) FROM data GROUP BY category;"), ("58 — Group count", "SELECT category, COUNT(*) FROM data GROUP BY category;"),
    ("59 — Filter", "SELECT * FROM data WHERE value > 0;"), ("60 — Multiple filter", "SELECT * FROM data WHERE value > 0 AND category = 'A';"),
    ("61 — Order", "SELECT * FROM data ORDER BY value DESC LIMIT 100;"), ("62 — Top N", "SELECT * FROM data ORDER BY value DESC LIMIT 10;"),
    ("63 — Case", "SELECT CASE WHEN value > 0 THEN 'positive' ELSE 'non-positive' END AS class, COUNT(*) FROM data GROUP BY 1;"),
    ("64 — Null handling", "SELECT COALESCE(column, 'Unknown') AS column_clean FROM data;"),
    ("65 — Date year", "SELECT EXTRACT(YEAR FROM date) AS year, COUNT(*) FROM data GROUP BY 1 ORDER BY 1;"),
    ("66 — Date month", "SELECT DATE_TRUNC('month', date) AS month, SUM(value) FROM data GROUP BY 1 ORDER BY 1;"),
    ("67 — Date range", "SELECT * FROM data WHERE date BETWEEN DATE '2025-01-01' AND DATE '2025-12-31';"),
    ("68 — Percent rank", "SELECT *, PERCENT_RANK() OVER (ORDER BY value) AS pct_rank FROM data;"),
    ("69 — Row number", "SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY value DESC) AS rn FROM data;"),
    ("70 — Running sum", "SELECT date, SUM(value) OVER (ORDER BY date) AS running_sum FROM data;"),
    ("71 — Moving average", "SELECT date, AVG(value) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS ma7 FROM data;"),
    ("72 — Lag", "SELECT date, value, LAG(value) OVER (ORDER BY date) AS previous_value FROM data;"),
    ("73 — Lead", "SELECT date, value, LEAD(value) OVER (ORDER BY date) AS next_value FROM data;"),
    ("74 — Duplicate keys", "SELECT key, COUNT(*) FROM data GROUP BY key HAVING COUNT(*) > 1;"),
    ("75 — Top per group", "SELECT * FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY value DESC) rn FROM data) WHERE rn <= 3;"),
    ("76 — Standard deviation", "SELECT category, STDDEV_POP(value) FROM data GROUP BY category;"),
    ("77 — Median", "SELECT MEDIAN(value) FROM data;"), ("78 — Quantile", "SELECT QUANTILE_CONT(value, 0.95) FROM data;"),
    ("79 — Correlation", "SELECT CORR(x, y) FROM data;"), ("80 — Covariance", "SELECT COVAR_POP(x, y) FROM data;"),
    ("81 — Distinct count", "SELECT COUNT(DISTINCT category) FROM data;"), ("82 — String length", "SELECT AVG(LENGTH(text)) FROM data;"),
    ("83 — Search text", "SELECT * FROM data WHERE LOWER(text) LIKE '%term%';"),
    ("84 — Create derived field", "SELECT *, price * quantity AS revenue FROM data;"),
    ("85 — Filter derived", "SELECT * FROM (SELECT *, price * quantity AS revenue FROM data) WHERE revenue > 100;"),
    ("86 — Pivot-like", "SELECT category, SUM(CASE WHEN region='EU' THEN value ELSE 0 END) AS eu_value FROM data GROUP BY category;"),
    ("87 — Duplicate rows", "SELECT *, COUNT(*) OVER (PARTITION BY a,b,c) AS duplicate_count FROM data;"),
    ("88 — Data range", "SELECT MIN(date), MAX(date), COUNT(*) FROM data;"),
    ("89 — Empty strings", "SELECT COUNT(*) FROM data WHERE TRIM(text) = '';"),
    ("90 — Type inspection", "DESCRIBE data;"), ("91 — Sample", "SELECT * FROM data USING SAMPLE 100 ROWS;"),
    ("92 — Export query", "COPY (SELECT * FROM data LIMIT 1000) TO 'result.csv' (HEADER, DELIMITER ',');"),
    ("93 — Parquet read", "SELECT * FROM read_parquet('data.parquet') LIMIT 100;"),
    ("94 — CSV read", "SELECT * FROM read_csv_auto('data.csv') LIMIT 100;"),
    ("95 — Join", "SELECT * FROM data d JOIN other o ON d.id = o.id;"),
    ("96 — Left join", "SELECT * FROM data d LEFT JOIN other o ON d.id = o.id;"),
    ("97 — Anti join", "SELECT d.* FROM data d ANTI JOIN other o ON d.id = o.id;"),
    ("98 — Union", "SELECT * FROM data UNION ALL SELECT * FROM other;"),
    ("99 — Explain", "EXPLAIN SELECT category, AVG(value) FROM data GROUP BY category;"),
    ("100 — Quality summary", "SELECT COUNT(*) rows, COUNT(*) FILTER (WHERE value IS NULL) missing_value, COUNT(DISTINCT category) categories FROM data;"),
]
ALL_MACROS = PYTHON_MACROS + SQL_MACROS
PYTHON_MACRO_TEXT = "\n\n".join(f"# {title}\n{code}" for title,code in PYTHON_MACROS)
SQL_MACRO_TEXT = "\n\n".join(f"-- {title}\n{code}" for title,code in SQL_MACROS)
