from __future__ import annotations

import json
from typing import Any, TypedDict
from pathlib import Path
from langchain_core.messages import AIMessage, BaseMessage
from langgraph.graph import END, StateGraph
try:
    from langgraph.checkpoint.memory import MemorySaver
except Exception:
    MemorySaver = None


class PresentationState(TypedDict, total=False):
    messages: list[BaseMessage]
    report_evidence: dict[str, Any]
    report_text: str
    plot_results: dict[str, Any]
    memory: list[dict[str, Any]]
    output_path: str
    title: str
    status: str
    summary: str
    error: str

def _json_safe(value):
    """Convert pandas/numpy-rich evidence into msgpack/JSON-safe primitives."""
    try:
        import pandas as pd
        import numpy as np
        if isinstance(value, pd.DataFrame):
            return {"__type__":"DataFrame","shape":[int(value.shape[0]),int(value.shape[1])],"columns":[str(c) for c in value.columns],"preview":value.head(20).to_dict(orient="records")}
        if isinstance(value, pd.Series): return value.head(50).tolist()
        if isinstance(value, dict): return {str(k): _json_safe(v) for k,v in value.items() if k not in {"model_object","figure"}}
        if isinstance(value, (list,tuple)): return [_json_safe(v) for v in value]
        if isinstance(value, np.ndarray): return value.tolist()
        if isinstance(value, (np.integer,np.floating)): return value.item()
    except Exception:
        pass
    try:
        json.dumps(value); return value
    except Exception:
        return str(value)


def _plan(state):
    evidence = _json_safe(state.get("report_evidence") or {})
    plots = _json_safe(state.get("plot_results") or evidence.get("data_visualizations") or {})
    nplots = len((plots or {}).get("plots", [])) if isinstance(plots, dict) else 0
    title = state.get("title") or "Data Science Analysis Presentation"
    summary = f"AI Agent Presentation plans a professional Streamlit presentation for '{title}' using the AI Agent Data Scientist, Plot and Report evidence, including {nplots} analytical visualizations."
    return {"status":"planned","summary":summary,"messages":[AIMessage(content=summary)],"memory":list(state.get("memory",[]))}


def _build(state):
    evidence = _json_safe(state.get("report_evidence") or {})
    plots = _json_safe(state.get("plot_results") or evidence.get("data_visualizations") or {})
    title = state.get("title") or "Data Science Analysis Presentation"
    target = evidence.get("target","Not specified")
    route = evidence.get("master_route","Not specified")
    ml = evidence.get("ML Agent") or {}
    dl = evidence.get("DL Agent") or {}
    report_text = state.get("report_text", "")
    plot_items = (plots or {}).get("plots", []) if isinstance(plots, dict) else []
    serializable_plots=[]
    for p in plot_items:
        serializable_plots.append({k:p.get(k) for k in ("title","kind","fields","rationale","insights","figure_json") if p.get(k) is not None})
    evidence_for_app = json.dumps(evidence, default=str)
    model_data = json.dumps({"ML Agent": ml, "DL Agent": dl}, default=str)
    plots_json = json.dumps(serializable_plots, default=str)
    code = f'''import streamlit as st
import json

st.set_page_config(page_title={title!r}, layout="wide")
st.title({title!r})
st.caption("Generated by Data Science Studio Pro — AI Agent Presentation")

st.header("Executive Summary")
st.write("This presentation combines the evidence and narrative produced by AI Agent Data Scientist, AI Agent Plot and AI Agent Report. It does not invent missing metrics or conclusions.")
col1, col2, col3 = st.columns(3)
col1.metric("Target", {target!r})
col2.metric("Master route", {route!r})
col3.metric("Analytical plots", {len(serializable_plots)})

st.header("Report Narrative")
st.markdown({report_text!r})

st.header("Analytical Visualizations")
plot_items = {plots_json}
for item in plot_items:
    st.subheader(item.get("title", "Visualization"))
    st.caption(item.get("rationale", ""))
    if item.get("insights"):
        for insight in item["insights"]:
            st.write("• " + str(insight))
    if item.get("figure_json"):
        try:
            import plotly.io as pio
            st.plotly_chart(pio.from_json(item["figure_json"]), use_container_width=True)
        except Exception as exc:
            st.warning("Visualization could not be rendered: " + str(exc))

st.header("Model Results")
st.json(json.loads({model_data!r}))

st.header("Governance & Human Oversight")
st.json(json.loads({json.dumps({"leakage_gate": evidence.get("leakage_gate"), "approvals": evidence.get("human_approval_evidence"), "agent_evaluation": evidence.get("agent_evaluation")}, default=str)!r}))

st.header("Evidence Appendix")
st.json(json.loads({evidence_for_app!r}))
'''
    output = state.get("output_path") or "DataScienceStudioPro_Presentation.py"
    Path(output).write_text(code, encoding="utf-8")
    return {"status":"complete","output_path":output,"summary":f"Generated Streamlit presentation with report and {len(serializable_plots)} analytical plots: {output}","messages":[AIMessage(content=f"Generated {output}")]}

workflow = StateGraph(PresentationState)
workflow.add_node("plan", _plan)
workflow.add_node("build", _build)
workflow.set_entry_point("plan")
workflow.add_edge("plan", "build")
workflow.add_edge("build", END)
agent_presentation_app = workflow.compile(checkpointer=MemorySaver()) if MemorySaver else workflow.compile()
