from __future__ import annotations

from typing import Any, TypedDict
from pathlib import Path
from langchain_core.messages import AIMessage, BaseMessage
from langgraph.graph import END, StateGraph
try:
    from langgraph.checkpoint.memory import MemorySaver
except Exception:
    MemorySaver = None

class PresentationState(TypedDict, total=False):
    messages: list[BaseMessage]
    report_evidence: dict[str, Any]
    report_text: str
    memory: list[dict[str, Any]]
    output_path: str
    title: str
    status: str
    summary: str
    error: str


def _plan(state):
    evidence = state.get("report_evidence") or {}
    title = state.get("title") or "Data Science Analysis Presentation"
    summary = f"AI Agent Presentation plans a professional Streamlit presentation for '{title}' using the AI Agent Report evidence."
    return {"status":"planned","summary":summary,"messages":[AIMessage(content=summary)],"memory":list(state.get("memory",[]))}


def _build(state):
    evidence = state.get("report_evidence") or {}
    title = state.get("title") or "Data Science Analysis Presentation"
    target = evidence.get("target","Not specified")
    route = evidence.get("master_route","Not specified")
    ml = evidence.get("ML Agent") or {}
    dl = evidence.get("DL Agent") or {}
    report_text = state.get("report_text", "")
    code = f'''import streamlit as st
import json

st.set_page_config(page_title={title!r}, layout="wide")
st.title({title!r})
st.caption("Generated by Data Science Studio Pro — AI Agent Presentation")

st.header("Executive Summary")
st.write("This presentation is generated from the evidence and narrative produced by AI Agent Report. It preserves recorded results and does not invent missing metrics.")

col1, col2, col3 = st.columns(3)
col1.metric("Target", {target!r})
col2.metric("Master route", {route!r})
col3.metric("Evidence items", {len(evidence)})

st.header("Report Narrative")
st.markdown({report_text!r})

st.header("Model Results")
model_data = {json.dumps({"ML Agent": ml, "DL Agent": dl}, default=str)}
st.json(model_data)

st.header("Governance & Human Oversight")
st.json({json.dumps({"leakage_gate": evidence.get("leakage_gate"), "approvals": evidence.get("human_approval_evidence"), "agent_evaluation": evidence.get("agent_evaluation")}, default=str)})

st.header("Evidence Appendix")
st.json({json.dumps(evidence, default=str)})
'''
    output = state.get("output_path") or "DataScienceStudioPro_Presentation.py"
    Path(output).write_text(code, encoding="utf-8")
    return {"status":"complete","output_path":output,"summary":f"Generated Streamlit presentation: {output}","messages":[AIMessage(content=f"Generated {output}")]}

workflow = StateGraph(PresentationState)
workflow.add_node("plan", _plan)
workflow.add_node("build", _build)
workflow.set_entry_point("plan")
workflow.add_edge("plan", "build")
workflow.add_edge("build", END)
agent_presentation_app = workflow.compile(checkpointer=MemorySaver()) if MemorySaver else workflow.compile()
